name: facelive
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.0 <4.0.0'
firebase_core: ^2.24.2
cloud_firestore: ^4.14.0
dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  firebase_core: ^2.24.2
  camera: ^0.10.5+9
  firebase_storage: ^11.6.0
  google_ml_kit: ^0.6.0
  permission_handler: ^11.0.1
  cloud_firestore: ^4.14.0
  path_provider: ^2.1.3
  firebase_ml_vision: ^0.12.0+3
  firebase_database: ^10.4.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

